### ISSUE TITLE
Windows support breaks Ansible Collection on Linux

### ISSUE THREAD

**Issue by rpelisse** [ansible-middleware/ansible_collections_jcliff#23]
Step to reproduce:

```
$ ansible-galaxy collection build --force .
Created collection for redhat.jcliff at /home/rpelisse/Repositories/redhat/ansible-jcliff-workspace/ansible_collections/redhat/jcliff/redhat-jcliff-0.0.1.tar.gz
$ ansible-galaxy collection install --force redhat-jcliff-0.0.1.tar.gz 
Process install dependency map
Starting collection install process
Installing 'redhat.jcliff:0.0.1' to '/home/rpelisse/.ansible/collections/ansible_collections/redhat/jcliff'
```

Run a simple playbook:

```
---
- hosts: localhost
  gather_facts: false
  vars:
    ansible_distribution: Fedora
    ansible_os_family: RedHat
    jboss_home: /path/to/jboss-eap-7.2.0/jboss-eap-7.2/
  collections:
    - redhat.jcliff
  roles:
    - jcliff
  tasks:

    - jcliff:
        wfly_home: "{{ jboss_home }}"
        subsystems:
          - system_props:
            - name: jcliff.enabled
              value: 'enabled.plus'
```

Running this playbook will lead Ansible to try to execute the powershell script:

```
PLAY [localhost] *********************************************************************************************************************************************

TASK [jcliff : Collect Supported Operating Systems] **********************************************************************************************************
ok: [localhost] => (item={'key': 'rpm', 'value': ['Fedora', 'CentOS', 'RedHat']})
ok: [localhost] => (item={'key': 'homebrew', 'value': ['MacOSX']})
ok: [localhost] => (item={'key': 'chocolatey', 'value': ['Windows']})

TASK [jcliff : Verify supported Operating Systems] ***********************************************************************************************************
ok: [localhost]

TASK [jcliff : Install JCliff using HomeBrew] ****************************************************************************************************************
skipping: [localhost]

TASK [jcliff : Install JCliff using Chocolatey] **************************************************************************************************************
skipping: [localhost]

TASK [jcliff : Install JCliff using RPM] *********************************************************************************************************************
included: /home/rpelisse/.ansible/collections/ansible_collections/redhat/jcliff/roles/jcliff/tasks/install_rpm.yml for localhost

TASK [jcliff : Add JCliff Yum Repository (Fedora)] ***********************************************************************************************************
ok: [localhost]

TASK [jcliff : Test if package jcliff is already installed] **************************************************************************************************
ok: [localhost]

TASK [jcliff : Install Jcliff using standalone binary] *******************************************************************************************************
skipping: [localhost]

TASK [jcliff] ************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "/bin/sh: powershell: command not found\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 127}

PLAY RECAP ***************************************************************************************************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0 

```
This is fixed by deleting the .ps1 scripts from the local install:

`rm ~/.ansible/collections/ansible_collections/redhat/jcliff/plugins/modules/jcliff.ps1`
